[package]
name = "omnimem-desktop"
description = "OmniMem's desktop app: tray or menu bar icon and settings window"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
arboard.workspace = true
auto-launch.workspace = true
keyring.workspace = true
omnimem-app.workspace = true
omnimem-core.workspace = true
omnimem-engine.workspace = true
omnimem-settings.workspace = true
open.workspace = true
serde_json.workspace = true
tao.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tray-icon.workspace = true
wry.workspace = true
