//! The skill compiler's pure functions against output the 6.x Python wrote
//! for the same inputs (`tests/fixtures/skills_golden.json`, generated by
//! running `memory/skills.py` and `memory/skill_compiler.py` from 6.7.1).
//! Rendering is byte for byte: a stored 6.x skill must recompile unchanged.

use serde_json::{Value, json};

use super::{held_back_preview, insufficient_note, pool_concentration};
use crate::skills::*;

fn fixture() -> Value {
    serde_json::from_str(include_str!("../tests/fixtures/skills_golden.json")).expect("fixture")
}

fn text(v: &Value, name: &str) -> String {
    v.get(name).and_then(Value::as_str).unwrap_or("").to_owned()
}

fn optional(v: &Value, name: &str) -> Option<String> {
    Some(text(v, name)).filter(|s| !s.is_empty())
}

fn strings(v: &Value) -> Vec<String> {
    v.as_array()
        .map(|a| {
            a.iter()
                .filter_map(|s| s.as_str().map(str::to_owned))
                .collect()
        })
        .unwrap_or_default()
}

fn pool_memory(v: &Value) -> PoolMemory {
    PoolMemory {
        key: text(v, "key"),
        content: text(v, "content"),
        project: optional(v, "project"),
        outcome: optional(v, "outcome"),
        breakthrough: optional(v, "breakthrough"),
        lesson: optional(v, "lesson"),
        gotchas: optional(v, "gotchas"),
        abandoned: v["abandoned"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|a| a.as_object().cloned())
            .collect(),
        blessed: v["blessed"].as_bool().unwrap(),
        created_at: v["created_at"].as_f64().unwrap(),
        updated_at: v["updated_at"].as_f64().unwrap(),
    }
}

fn pool(v: &Value) -> Vec<PoolMemory> {
    v.as_array().unwrap().iter().map(pool_memory).collect()
}

fn kind(name: &str) -> &'static str {
    match name {
        "do" => "do",
        "watch" => "watch",
        "dont" => "dont",
        "ref" => "ref",
        "feed" => "feed",
        other => panic!("unknown rule kind {other}"),
    }
}

fn rule(v: &Value) -> Rule {
    Rule {
        kind: kind(&text(v, "kind")),
        text: text(v, "text"),
        sources: strings(&v["sources"]),
        reinforcement: v["reinforcement"].as_u64().unwrap() as usize,
        blessed: v.get("blessed").and_then(Value::as_bool).unwrap_or(false),
        name: optional(v, "name"),
        approach_type: text(v, "approach_type"),
        projects: v.get("projects").map(strings).unwrap_or_default(),
        url: text(v, "url"),
        feed: text(v, "feed"),
        influence: v.get("influence").and_then(Value::as_i64).unwrap_or(0),
    }
}

fn assert_same_text(actual: &str, expected: &str, label: &str) {
    if actual == expected {
        return;
    }
    for (i, (a, e)) in actual.split('\n').zip(expected.split('\n')).enumerate() {
        assert_eq!(a, e, "{label}: line {} differs", i + 1);
    }
    panic!(
        "{label}: same lines but different lengths ({} vs {} bytes)",
        actual.len(),
        expected.len()
    );
}

#[test]
fn lessons_match_python() {
    let f = fixture();
    let pool = pool(&f["pool"]);
    for (field, graveyard) in [("lessons", true), ("lessons_no_graveyard", false)] {
        let actual = extract_lessons(&pool, graveyard);
        let expected = f[field].as_array().unwrap();
        assert_eq!(actual.len(), expected.len(), "{field}");
        for (a, e) in actual.iter().zip(expected) {
            assert_eq!(a.kind, e["kind"], "{field}");
            assert_eq!(a.text, e["text"], "{field}");
            assert_eq!(a.source_key, e["source_key"], "{field}");
            assert_eq!(
                a.source_updated_at,
                e["source_updated_at"].as_f64().unwrap()
            );
            assert_eq!(a.blessed, e["blessed"]);
            assert_eq!(a.project.as_deref(), e["project"].as_str(), "{field}");
            assert_eq!(a.name.as_deref(), e["name"].as_str(), "{field}");
            assert_eq!(a.approach_type, e["approach_type"], "{field}");
        }
    }
    let bearing: Vec<bool> = pool.iter().map(lesson_bearing).collect();
    assert_eq!(json!(bearing), f["lesson_bearing"]);
}

#[test]
fn rendered_bodies_match_python_byte_for_byte() {
    let f = fixture();
    let rules: Vec<Rule> = f["rules"].as_array().unwrap().iter().map(rule).collect();
    for render in f["renders"].as_array().unwrap() {
        let chosen: Vec<Rule> = render["rule_indices"]
            .as_array()
            .unwrap()
            .iter()
            .map(|i| rules[i.as_u64().unwrap() as usize].clone())
            .collect();
        let body = render_skill_md(
            "python",
            "local",
            render["description"].as_str().unwrap(),
            &chosen,
            render["compiled_at"].as_f64().unwrap(),
            render["min_reinforcement"].as_u64().unwrap() as usize,
        );
        assert_same_text(
            &body,
            render["body"].as_str().unwrap(),
            &text(render, "name"),
        );
    }
}

#[test]
fn reference_and_feed_rules_match_python() {
    let f = fixture();
    let promoted: Vec<PromotedItem> = f["promoted"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| PromotedItem {
            key: text(p, "key"),
            content: text(p, "content"),
            title: text(p, "title"),
            source_url: text(p, "source_url"),
            skill_rules: p["skill_rules"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| ReferenceRule {
                    kind: text(r, "kind"),
                    text: text(r, "text"),
                })
                .collect(),
            promoted_at: 0.0,
        })
        .collect();
    let refs: Vec<Value> = build_reference_rules(&promoted)
        .iter()
        .map(Rule::to_value)
        .collect();
    assert_eq!(Value::Array(refs), f["reference_rules"]);

    let articles: Vec<FeedArticle> = f["articles"]
        .as_array()
        .unwrap()
        .iter()
        .map(|a| FeedArticle {
            key: text(a, "key"),
            content: text(a, "content"),
            title: text(a, "title"),
            feed_name: text(a, "feed_name"),
            influence: a["influence"].as_i64().unwrap(),
            source_url: text(a, "source_url"),
            created_at: 0.0,
        })
        .collect();
    let feeds: Vec<Value> = build_feed_rules(&articles)
        .iter()
        .map(Rule::to_value)
        .collect();
    assert_eq!(Value::Array(feeds), f["feed_rules"]);
}

#[test]
fn rule_changes_match_python() {
    let f = fixture();
    let changes = summarise_rule_changes(
        f["old_manifest"].as_array().unwrap(),
        f["new_manifest"].as_array().unwrap(),
    );
    assert_eq!(Value::Array(changes), f["changes"]);
}

#[test]
fn review_notes_match_python() {
    let f = fixture();
    let held: Vec<Rule> = f["held_back_inputs"]
        .as_array()
        .unwrap()
        .iter()
        .map(rule)
        .collect();
    assert_eq!(
        Value::Array(held_back_preview(&held, 10)),
        f["held_back_preview"]
    );

    let mixed = pool(&f["pool"]);
    assert_eq!(
        pool_concentration(&mixed).unwrap_or(Value::Null),
        f["pool_concentration"]
    );
    assert_eq!(
        insufficient_note("python", &mixed, &held),
        f["insufficient_note_mixed"]
    );
    let single = pool(&f["single_project_pool"]);
    assert_eq!(
        insufficient_note("python", &single, &held[1..2]),
        f["insufficient_note_single"]
    );
}

#[test]
fn text_helpers_match_python() {
    let f = fixture();
    assert_eq!(
        strip_volatile(f["strip_volatile_input"].as_str().unwrap()),
        f["strip_volatile"]
    );
    for case in f["one_line"].as_array().unwrap() {
        let limit = case[1].as_u64().unwrap() as usize;
        assert_eq!(one_line(case[0].as_str().unwrap(), limit), case[2]);
    }
}
