"""Write reference_vectors.json: full vectors from the Python 6.7 ONNX engine.

The Rust engine must reproduce these to within float noise, so the store a
6.7 instance built needs no re-embedding and no threshold moves. Run from the
repo root with the Python test environment, offline against the HF cache:

    HF_HUB_OFFLINE=1 .venv-test/bin/python \
        crates/omnimem-embed/tests/fixtures/generate_reference.py

The texts cover what can silently diverge between two tokeniser/pooling
implementations: plain prose, the two vectors the Python suite already pins,
non-ASCII (accents, CJK, emoji, combining characters), an empty string,
whitespace runs, text past the 256-token cap (truncation), and a batch whose
members differ in length (padding must not leak into mean pooling).
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "..", "..", "mcp_server"))

from memory import onnx_embedding as oe  # noqa: E402

TEXTS = [
    "Decision: use uv for packaging.",
    "The FT.SEARCH tag filter matches raw values only.",
    "valkey-py's dropindex() sends a trailing empty argument that valkey-search rejects",
    "Café crème brûlée, naïve façade",
    "Café with a combining accent",
    "日本語のテキストと絵文字 🚀🔥",
    "",
    "   lots\t\tof   \n\n whitespace   ",
    " ".join(["long memory text that runs well past the token cap"] * 60),
]

BATCH = [TEXTS[0], TEXTS[8], TEXTS[5]]


def main() -> None:
    engine = oe.OnnxSentenceEmbedding("all-MiniLM-L6-v2")
    engine.load()
    singles = [engine.encode(t).tolist() for t in TEXTS]
    batched = engine.encode(BATCH).tolist()
    out = {
        "model": engine.repo,
        "revision": engine.revision,
        "onnx_file": engine.onnx_file,
        "pooling": engine.pooling,
        "max_seq_length": engine.max_seq_length,
        "dimension": engine.dimension,
        "note": "Generated by generate_reference.py from the Python 6.7 ONNX engine.",
        "singles": [{"text": t, "vector": v} for t, v in zip(TEXTS, singles)],
        "batch": {"texts": BATCH, "vectors": batched},
    }
    path = os.path.join(HERE, "reference_vectors.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(out, fh, ensure_ascii=False)
        fh.write("\n")
    print(f"wrote {path}: {len(TEXTS)} singles, batch of {len(BATCH)}, dim {engine.dimension}")


if __name__ == "__main__":
    main()
