"""Provenance class on memories (v6.6.2): where did this come from?

Every memory carries a ``provenance`` field with one of three values:

    retrieved   from an external source — an RSS article, a page summary,
                a fact looked up somewhere else.
    concluded   generated by the system's own reasoning — the agent's
                write-up of work done, an inference, a compiled draft.
    asserted    stated directly by the human — a preference, a project
                description, a rule they dictated.

Why it exists: without it, an inference the system made last month is
recalled today and read as independent corroboration for the reasoning
that produced it, so errors compound with no external correction. A
buyer of a curated store in a regulated domain is buying exactly this
traceability.

Two decisions this module encodes deliberately. First, the field is
reported and never scored on — landing it and changing what recall does
with it are separate releases so a benchmark move can be attributed.
Second, the awkward backfill: an episodic memory is the agent's write-up
of work that really happened — the conclusion is the system's, the
grounding is real. Defaulting all of it to ``concluded`` is technically
honest and unfair to the most valuable material in the store, and it is
the class a buyer scrutinises first. It is the chosen default anyway,
because the alternative is a guess in the other direction; the human can
reclassify a memory they vouch for with set_provenance(...,
provenance="asserted").

This axis is independent of ``licence`` (redistribution rights): a
retrieved article can be open or restricted, and asserted content is
usually — but not necessarily — our own.

The vocabulary is kept in one place (PROVENANCE_CLASSES) because the v7
Mycelium ``ClusterSummary`` carries a ``provenance_class`` that must use
the same values; a mismatch there would be silent until cluster time.
"""

from __future__ import annotations

from .lineage import (  # noqa: F401 — is_classifiable_key/stamp_lineage re-exported
    is_classifiable_key,
    normalise_alias_key,
    stamp_lineage,
)

PROVENANCE_RETRIEVED = "retrieved"
PROVENANCE_CONCLUDED = "concluded"
PROVENANCE_ASSERTED = "asserted"

PROVENANCE_CLASSES: tuple[str, ...] = (
    PROVENANCE_RETRIEVED, PROVENANCE_CONCLUDED, PROVENANCE_ASSERTED,
)

PROVENANCE_LABELS: dict[str, str] = {
    PROVENANCE_RETRIEVED: "Retrieved (external source)",
    PROVENANCE_CONCLUDED: "Concluded (system reasoning)",
    PROVENANCE_ASSERTED: "Asserted (stated by the human)",
}

# (value, label) pairs for form selects, in vocabulary order.
PROVENANCE_CHOICES: list[tuple[str, str]] = [
    (value, PROVENANCE_LABELS[value]) for value in PROVENANCE_CLASSES
]

# Synonyms a human is likely to reach for. Kept small on purpose: the
# classes are the contract, the aliases are a convenience.
PROVENANCE_ALIASES: dict[str, str] = {
    "retrieved": PROVENANCE_RETRIEVED,
    "external": PROVENANCE_RETRIEVED,
    "source": PROVENANCE_RETRIEVED,
    "looked-up": PROVENANCE_RETRIEVED,
    "concluded": PROVENANCE_CONCLUDED,
    "inferred": PROVENANCE_CONCLUDED,
    "derived": PROVENANCE_CONCLUDED,
    "reasoned": PROVENANCE_CONCLUDED,
    "system": PROVENANCE_CONCLUDED,
    "asserted": PROVENANCE_ASSERTED,
    "stated": PROVENANCE_ASSERTED,
    "user": PROVENANCE_ASSERTED,
    "human": PROVENANCE_ASSERTED,
    "dictated": PROVENANCE_ASSERTED,
}

# What each namespace's writes are, absent a declaration. Preferences are
# what the human told us; knowledge is what was fetched from elsewhere;
# episodic and project memories are the agent's account of the work. (A
# project *context* entry is asserted, but that is set_project_context's
# explicit stamp — a remember(namespace="project") write is a write-up
# like any other, and the backfill treats it the same way.)
_NAMESPACE_DEFAULTS: dict[str, str] = {
    "episodic": PROVENANCE_CONCLUDED,
    "project": PROVENANCE_CONCLUDED,
    "preference": PROVENANCE_ASSERTED,
    "knowledge": PROVENANCE_RETRIEVED,
}


def resolve_provenance(raw: str | None) -> str:
    """Resolve a declared provenance (class or alias) to a class.

    Raises ValueError for anything unrecognised — there is no "unknown"
    provenance, so a value must be one of the three or not given at all.
    """
    try:
        return PROVENANCE_ALIASES[normalise_alias_key(raw)]
    except KeyError:
        raise ValueError(
            f"Unrecognised provenance {raw!r}. Use one of "
            f"{', '.join(PROVENANCE_CLASSES)}."
        ) from None


def validate_provenance_class(value: str) -> str:
    """Accept only a bare class (for stored values and filters)."""
    if value not in PROVENANCE_CLASSES:
        raise ValueError(
            f"Invalid provenance class {value!r}. Must be one of "
            f"{', '.join(PROVENANCE_CLASSES)}."
        )
    return value


def default_provenance(namespace: str) -> str:
    """Provenance stamped on a write that declares none."""
    return _NAMESPACE_DEFAULTS.get(namespace, PROVENANCE_CONCLUDED)


def provenance_for_write(raw: str | None, namespace: str) -> str:
    """Provenance for a new write: the declared class, or the namespace
    default. An empty string means "not given". Shared by the remember()
    tools and the web UI's create form."""
    if not raw:
        return default_provenance(namespace)
    return resolve_provenance(raw)


def effective_provenance(doc: dict, namespace: str, key: str | None = None) -> str:
    """The provenance a stored record has, or would have had.

    A read-time fallback for records the backfill has not reached — an
    article ingested by a worker image that predates the field during a
    rolling upgrade, or a read between an upgrade and the restart that
    backfills. Follows migrate_provenance's rules: an article is retrieved,
    a preference or a project context entry (its key is mem:project:{name})
    asserted, and everything else — a legacy plain knowledge write, an
    episodic memory — concluded. A fact is concluded too, since its source
    can't be consulted here; the backfill inherits the source's class, so
    a fact of a preference reads concluded until then.
    Note this is NOT the write-time default (a new plain knowledge write is
    retrieved): an unstamped record is by definition a legacy one. An
    out-of-vocabulary stored value reads as absent rather than passing
    through, so a filter can never fail to match what recall reports.
    """
    stored = doc.get("provenance")
    if stored in PROVENANCE_CLASSES:
        return stored
    if doc.get("feed_name"):
        return PROVENANCE_RETRIEVED
    if doc.get("enriched_from"):
        return PROVENANCE_CONCLUDED
    if namespace == "preference":
        return PROVENANCE_ASSERTED
    if namespace == "project":
        name = doc.get("project_name")
        if (name and key == f"mem:project:{name}") or doc.get("stack") or doc.get("goals"):
            return PROVENANCE_ASSERTED
    return PROVENANCE_CONCLUDED


def classify_provenance(store, keys: list[str], provenance: str) -> dict[str, list[str]]:
    """Record a provenance on stored memories and cascade it to their facts.

    A fact extracted from a memory is a restatement, not new reasoning, so
    it carries its source's provenance. Shared by the set_provenance tool
    and the web UI's detail form.
    """
    return stamp_lineage(store, keys, {"provenance": validate_provenance_class(provenance)})
